### ISSUE TITLE
error I came across in part_00

### ISSUE THREAD

**Issue by gratten** [cmdruid/nostr-socket-workshop#1]
error received:
CustomError: Cannot find module '/home/[username]/nostr-socket-workshop/part_00/node_modules/@scure/bip39/wordlists/english' imported from /home/[username]/nostr-socket-workshop/part_00/node_modules/nostr-tools/lib/esm/nostr.mjs

solution:
navigate to:
cd /home/[username]/nostr-socket-workshop/part_00/node_modules/nostr-tools/lib/esm/

modify:
import { wordlist } from "@scure/bip39/wordlists/english";
to:
import { wordlist } from "@scure/bip39/wordlists/english.js";

seems this is a known issue with nostr-tools at the moment.
https://github.com/nbd-wtf/nostr-tools/issues/253

**Comment by cmdruid** [comment]
Yes this is a known issue. Hopefully it is resolved soon. In the meantime, I'll make sure the version specified in the package.json for this course does not use the version with this bug. Thank you for reporting it!
